version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo installing maven...
      - apt-get update -y
      - apt-get install -y maven
  build:
    commands:
      - mvn install
      - mvn package
      - sam package
        --template-file template.yml
        --s3-bucket iit-cloud
        --output-template-file packaged-template.yml
artifacts:
  files:
    - target/HelloWorld-1.0.jar