version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - pip install --upgrade 'six==1.15.0'
      - mvn package
      - sam package
        --template-file template.yml
        --s3-bucket iit-cloud
        --output-template-file packaged-template.yml
artifacts:
  files:
    - target/HelloWorld-1.0.jar